### ISSUE TITLE
Custom Inspector And Gizmo For Railroad Builder

### ISSUE THREAD

**Issue by aditya12125454** [Battlehub0x/RTE_Docs#107]
i am making train simulation game and i want to get this type of gizmo and inspector in rteditor
![Screenshot 2024-03-16 082517](https://github.com/Battlehub0x/RTE_Docs/assets/98509205/ee014e20-e3ec-4b0c-945b-3088fd640608)

**Comment by Battlehub0x** [comment]
Either I don't understand the question or if there are any specific questions here, but there is an extension Assets\Battlehub\RTExtensions\Runtime\RTDeformer that is similar and might be a good starting point for this.
