### ISSUE TITLE
MenuItem does not behave correctly when hovering in Unity 2021.3

### ISSUE THREAD

**Issue by Battlehub0x** [Battlehub0x/RTE_Docs#17]
Hey guys, clicking on menu items is a bit buggy how can I fix that

First there's this weird mouse over behavior that makes it hard to interact with the drop downs, trying to add a gif now

is it the problem that when you enter an Area and it has a child Area that also has RaycastTarget? if so ,that beacause the UGUI in new version of unity has Changed the behavior of hover/unhover event, it will trigger exit when you enter sub area and then trigger enter on sub area. On Unity2018 it will not trigger exit and enter on this condition.

**Comment by Battlehub0x** [comment]
Fixed here https://github.com/Battlehub0x/RTE_AssetStore/commit/2e2a824ab7304c85099d5b582fb9ef14c951b5eb

**Comment by dlucio** [comment]
Hi @Battlehub0x 
When will this actualization be available in the Unity Asset Store?
