### ISSUE TITLE
It is not possible to deactivate parts of tree item during layout rebuild loop

### ISSUE THREAD

**Issue by BattlehubCode** [Battlehub0x/RTE_Docs#2]
Hi,guys,I follow the manual here: https://rteditor.battlehub.net/manual/vtv.html#getting-started and create a tree view to show my custom data items.what's the correct way to hide the icon of the items?tried the code here but this error occurs
![hide](https://user-images.githubusercontent.com/15802443/153870425-53e191ba-ef30-4ff4-bf67-7f345e136728.png)
![error (2)](https://user-images.githubusercontent.com/15802443/153870435-34753781-688b-4c14-95d1-cf12fccc3d69.png)
:

**Comment by Battlehub0x** [comment]
I suggest you use CanvasGroup.alpha instead of deactivating the tree view item parts:
https://docs.unity3d.com/ScriptReference/CanvasGroup-alpha.html

If for some reason this is not possible, here is a possible approach:

  ```
private async void OnItemDataBinding(object sender, VirtualizingTreeViewItemDataBindingArgs e)
        {
            DataItem dataItem = e.Item as DataItem;
            if (dataItem != null)
            {
                //We display dataItem.name using UI.Text 
                TextMeshProUGUI text = e.ItemPresenter.GetComponentInChildren<TextMeshProUGUI>(true);
                text.text = dataItem.Name;

                //Load icon from resources
                Image icon = e.ItemPresenter.GetComponentsInChildren<Image>(true)[4];
                icon.sprite = Resources.Load<Sprite>("IconNew");

                //And specify whether data item has children (to display expander arrow if needed)
                e.HasChildren = m_filteredItems.Count == 0 && dataItem.Children.Count > 0;

                if (CanvasUpdateRegistry.IsRebuildingLayout())
                {
                    await Task.Yield();
                }

                icon.gameObject.SetActive(false);
            }     
        }
```
