### ISSUE TITLE
How to modify inspector window

### ISSUE THREAD

**Issue by sajadmowlaei** [Battlehub0x/RTE_Docs#38]
Hello,

I need to make some changes in the inspector, I wonder what is the best way.
I need to remove "Add Component" button, remove component button, enable/disable checkmark, and layers. I marked them in the attached picture.

Thank you for your support
![1](https://user-images.githubusercontent.com/20297033/175510473-16eda588-f124-4ffa-9825-14a595682a22.PNG)
.

**Comment by Battlehub0x** [comment]
Hello, here is an example of how to disable the LayersEditor, Add Component and Remove Component buttons:

```
using Battlehub.RTCommon;
using Battlehub.RTEditor;

public class CustomizeInspectorExample : EditorExtension
{
    protected override void OnInit()
    {
        base.OnInit();

        ISettingsComponent settingsComponent = IOC.Resolve<ISettingsComponent>();
        InspectorSettings inspectorSettings = settingsComponent.BuiltInWindowsSettings.Inspector;

        InspectorSettings.GameObjectEditorSettings goEditorSettings = inspectorSettings.GameObjectEditor;
        goEditorSettings.ShowAddComponentButton = false;
        goEditorSettings.ShowLayers = false;
        goEditorSettings.ComponentEditor.ShowRemoveButton = false;

        //goEditorSettings.ShowIsActiveToggle = false;
    }

    protected override void OnCleanup()
    {
        base.OnCleanup();
    }
}
```

**Comment by Battlehub0x** [comment]
[Assets.zip](https://github.com/Battlehub0x/RTE_Docs/files/9039326/Assets.zip)

As for the enable/disable checkmark replace SettingsComponent.cs and GameObjectEditor.cs with files from attachments and uncomment //goEditorSettings.ShowIsActiveToggle = false; in the example above.
