### ISSUE TITLE
How to modify right click menu in projectView

### ISSUE THREAD

**Issue by sajadmowlaei** [Battlehub0x/RTE_Docs#40]
Hi,
If I right click on the project (on items or on empty space), I see a "create" option that has three options (Folder, Material, Animation Clip). I want to remove them since they has no use in my application. What is the best way to remove them?
Thanks.
![2](https://user-images.githubusercontent.com/20297033/175548324-cd962dcd-02f3-4c09-ace9-0a9a7b725ea5.PNG)

**Comment by Battlehub0x** [comment]
![image](https://user-images.githubusercontent.com/15802443/177154832-358dd36b-5487-4063-a5b6-4c8b402966d4.png)

Please see Scene10 - Extending Context Menu Example. From this example you can learn how to override the context menu in a ProjectTreeViewModel. The process for ProjectFolderViewModel should be the same.
