### ISSUE TITLE
Hello, I need to hide "Edit", and from" Game Objects" the "Empty" and the "3D Object" menu items.

### ISSUE THREAD

**Issue by Battlehub0x** [Battlehub0x/RTE_Docs#42]
Hello, I need to hide "Edit", and from" Game Objects" the "Empty" and the "3D Object" menu items.
What i tried so far
  [MenuCommand("MenuEdit", hide: true)]
  public static void HideEdit() { }

  [MenuCommand("MenuGameObject/Empty", hide: true)]
  public static void HideGameObjectEmpty() { }

  [MenuCommand("MenuGameObject/3D Object", hide: true)]
  public static void HideGameObject3DObject() { }
Edit works as expected, but the other two are still there. Any advice?

**Comment by bryansq2nt** [comment]
How do i add this code to the scene ?
I tried to create a new script with the code you provided but unity shows an error:

Can't add script behaviour 'HideMenu'. The script needs to derive from MonoBehaviour!
