### ISSUE TITLE
Getting Started guide steps are different on local machine

### ISSUE THREAD

**Issue by jasjae** [Battlehub0x/RTE_Docs#46]
Unity version: Unity 2021.3.7f1 Personal

I'm following the instruction on the site:
https://rteditor.battlehub.net/manual/runtime-editor.html#getting-started

and following these steps:
1. Install Battlehub/1 Universal RP Support [Your Version] package
2. Install Battlehub/RTEditor Demo package
but step 3 does not appear
3. Click Tools->Runtime Editor->Use built-in RenderPipelineAsset, then click "Yes"

My menu looks like the screenshot
![image](https://user-images.githubusercontent.com/34994669/187808662-3581be80-84b4-4ea3-91da-841b521349ae.png)

And I get 28 errors after step 2, first error:
Assets\Battlehub\RTExtensionsURP\Runtime\RTBuilder\PBSelectionPickerRendererURP.cs(7,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

**Comment by Battlehub0x** [comment]
Please install the latest version of Universal Render Pipeline using Package Manager.  The reason I removed the "1 Universal RP Support [your version]" package is that it was installing Universal Render Pipeline with the wrong minor version, which was causing problems. Therefore, please install the Universal Render Pipeline and repeat the steps.

![image](https://user-images.githubusercontent.com/15802443/187924733-125c3e54-026d-4dd4-8e93-da20c202b56d.png)
