### ISSUE TITLE
Transform Handle is greyed out

### ISSUE THREAD

**Issue by Zumbalamambo** [Battlehub0x/RTE_Docs#47]
I have selected a 3D object and enabled editing. for some reason, the gizmo is greyed out on selection. why? and sometimes I’m not even able to edit it though I have enabled editing and turned on all settings.

**Comment by Battlehub0x** [comment]
I think this is because the object you have selected is static

![image](https://user-images.githubusercontent.com/15802443/192267128-04daae02-78e7-4626-951e-943d3b42f744.png)
