### ISSUE TITLE
Treeview expand arrow not being removed when deleting child folder

### ISSUE THREAD

**Issue by Filippoml** [Battlehub0x/RTE_Docs#48]
https://user-images.githubusercontent.com/14567796/191233959-6f7601de-30c7-476d-9ec4-4db8bec623fe.mp4

It works when the parent folder is expanded.
It doesn't work when the parent folder is not expanded.

**Comment by Battlehub0x** [comment]
Fixed/no longer reproducible in Runtime Editor 4.1.2.
