### ISSUE TITLE
is there a way to select a root gameobject as the parent for everything?

### ISSUE THREAD

**Issue by joaquingrech** [Battlehub0x/RTE_Docs#69]
Is there a way to select a root gameobject as the parent for everything you do in the editor?
This means that if I create anything new, duplicate, or whatever, instead of being at the root of the unity hierarchy, it would all be under my "root" gameobject.

**Comment by Battlehub0x** [comment]
This is a little bit hacky, and I didn't test it too much, but seems like following approach will work:

1. Create following script:

```
using Battlehub.RTCommon;
using UnityEngine;

namespace Battlehub.RTEditor.Examples
{
    public class SetObjectRoot : EditorExtension
    {
        private IRTE m_rte;

        [SerializeField]
        private GameObject m_root;

        protected override void OnInit()
        {
            base.OnInit();
            m_rte = IOC.Resolve<IRTE>();
            m_rte.Object.Started += Object_Started; 
        }

   
        protected override void OnDestroy()
        {
            base.OnDestroy();
            m_rte.Object.Started -= Object_Started;
        }

        private void Object_Started(ExposeToEditor obj)
        {
            if (obj.transform.parent == null)
            {
                obj.transform.SetParent(m_root.transform, true);
            }
        }
    }
}

```
2. Create and use HierarcyRoot tag as following

![image](https://user-images.githubusercontent.com/15802443/207297010-7b77b533-cb23-4b1b-b136-2ac676355731.png)

![image](https://user-images.githubusercontent.com/15802443/207296925-38a8a19d-a2fa-4716-be67-ed523f2e5fd2.png)
