### ISSUE TITLE
How to extent WindowManager?

### ISSUE THREAD

**Issue by sajadmowlaei** [Battlehub0x/RTE_Docs#7]
Hi,
I need to add more functionality to the WindowManager, but I could not found in the documentation how I can register my custom class instead of  WindowManager. Did I missed something in the documentation? If it is not there, what is the best way?
Thank you in advance.

**Comment by Battlehub0x** [comment]
Hello, thank you for contacting me with this issue. The window manager has no virtual methods that can be overridden.So there is no point in replacing it with derived custom class.  You can add new functionality by creating a class derived from EditorExtension. Could you please give examples of what functionality you want to add?

**Comment by sajadmowlaei** [comment]
Hi, Thanks for the response.
I had a custom window that needs some initialization, I wanted to put the logic in WindowManager. EditorExtention is a good idea. 
Thanks.

**Comment by Battlehub0x** [comment]
You can also use the RuntimeWindowExtension, which is designed to extend existing and custom windows. For example you can add additional layers to an existing window.

```
using Battlehub.RTCommon;
using Battlehub.UIControls;
using UnityEngine;

namespace Battlehub.RTEditor.Examples.Scene71
{
    public class ProBuilderSceneLayerInitExample : RuntimeWindowExtension
    {
        [SerializeField]
        private RectTransform m_probuilderTools = null;

        public override string WindowTypeName => BuiltInWindowNames.Scene;

        protected override void Extend(RuntimeWindow window)
        {
            if(m_probuilderTools != null)
            {
                RectTransform layer = Instantiate(m_probuilderTools, window.ViewRoot);
                layer.Stretch();
            }
        }
    }
}
```
