### ISSUE TITLE
how do you add to the built-in library?

### ISSUE THREAD

**Issue by joaquingrech** [Battlehub0x/RTE_Docs#70]
I want to add materials to the built-in library so that it is available on play without the need to "import" every time.
How can this be achieved?

**Comment by Battlehub0x** [comment]
Hi, please take a look at 
Assets\Battlehub\RTEditorDemo\Runtime\Scenes\Scene100 - Legacy Examples\ImportDefaultAssetsExample.cs

```
using Battlehub.RTCommon;
using Battlehub.RTSL.Interface;

using System.Linq;
using UnityEngine;

namespace Battlehub.RTEditor.Demo
{
    public class ImportDefaultAssetsExample : EditorExtension
    {
        public bool FirstRun
        {
            get { return PlayerPrefs.GetInt("FirstRun", 1) == 1; }
            set { PlayerPrefs.SetInt("FirstRun", value ? 1 : 0); }
        }

        // Uncomment to delete "FirstRun" key using context menu
        //[UnityEngine.ContextMenu("Clear PlayerPrefs")]
        //public void ClearPlayerPrefs()
        //{
        //    PlayerPrefs.DeleteKey("FirstRun");
        //}

        protected override void OnEditorExist()
        {
            base.OnEditorExist();

            if (!FirstRun)
            {
                return;
            }
            FirstRun = false;

            IProject project = IOC.Resolve<IProject>();
            IRTE editor = IOC.Resolve<IRTE>();

            project.LoadImportItems("DemoAssetLibrary", true, (error, root) =>
            {
                if (error.HasError)
                {
                    editor.IsBusy = false;
                    Debug.LogError(error.ToString());
                }
                else
                {
                    IResourcePreviewUtility resourcePreview = IOC.Resolve<IResourcePreviewUtility>();
                    ImportAssetItem[] importItems = root.Flatten(true).OfType<ImportAssetItem>().ToArray();
                    for (int i = 0; i < importItems.Length; ++i)
                    {
                        ImportAssetItem importItem = importItems[i];
                        importItem.SetPreview(resourcePreview.CreatePreviewData(importItems[i].Object));
                    }
                    project.UnloadImportItems(root);

                    project.Import(importItems, (importError, assetItems) =>
                    {
                        if (importError.HasError)
                        {
                            Debug.LogError(importError.ErrorText);
                        }

                        editor.IsBusy = false;
                    });
                }
            });
        }
    }
}

```

The above example imports the "DemoAssetLibrary" asset library the first time the application is started.

**Comment by joaquingrech** [comment]
This didn't work for me. I removed the DemoAssetLibrary to avoid conflict.
Created a new DefaultAssetLibrary using Tools/Runtime SaveLoad/Create runtime asset library.
I placed it into a Resources folder.
Then I dragged my materials folder into it. I see them and they all have some ID.

When I run it, nothing shows up on the list.
So I began looking at errors and warnings. And I get this warning:
RTSLTypeModel.dll was not found. Please build type model using the Build All button available through the Tools->Runtime SaveLoad->Config menu item
UnityEngine.Debug:LogWarning (object)

I go and hit those, Tools/Runtime/Config... and build all. It does it thing and it says persistent classes created.
Then the editor begins compiling some scripts and it throws one error:
Property _BaseMap_ST already exists in the property sheet with a different type: 3
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Battlehub.RTSL.RuntimeShaderProfilesGen:Create () (at Assets/Battlehub/RTEditor/Editor/RTSL/RuntimeShaderProfilesGen.cs:61)
Battlehub.RTSL.RuntimeShaderProfilesGen:CreateProfile () (at Assets/Battlehub/RTEditor/Editor/RTSL/RuntimeShaderProfilesGen.cs:23)
Battlehub.RTSL.Menu:CreateShaderProfiles () (at Assets/Battlehub/RTEditor/Editor/RTSL/Menu.cs:425)
Battlehub.RTSL.Menu:OnScriptsReloaded () (at Assets/Battlehub/RTEditor/Editor/RTSL/Menu.cs:509)

But it continues and builds the list and everything else. I have no idea why that error in there.

I hit play, and same warning:
RTSLTypeModel.dll was not found. Please build type model using the Build All button available through the Tools->Runtime SaveLoad->Config menu item
UnityEngine.Debug:LogWarning (object)

I try to assign a material to a cube, but nothing is in my asset library. Empty, not even the demo assets.

**Comment by joaquingrech** [comment]
The bug is that the editor is not cleaning up the project folder when you build the libraries or anything.
I went into
C:\Users\myname\AppData\LocalLow\DefaultCompany\CreatorProject\DefaultProject
And I found the whole Demo project folder structure with all the imported junk in there. None of those files exist on my project because I deleted them to make sure it was not interfering.
I deleted that folder, clean. Hit play and... it works.

You need to delete that folder or no matter how many times you update the library, build all or whatever you do, will work. Because it will continue loading whatever it finds in there.
