### ISSUE TITLE
How do i change the lenght of an animation

### ISSUE THREAD

**Issue by LucaBiada** [Battlehub0x/RTE_Docs#74]
The animation window by default creates a clip with 60samples, maybe i'm dumb but didnt find a way to make it longer

**Comment by Battlehub0x** [comment]
Hi, there is defaultClipLength field in AnimationTimelineView. 

![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/29bba1b7-e956-4151-b3cf-b87812d45abb)
