### ISSUE TITLE
Runtime scripting on Android

### ISSUE THREAD

**Issue by danielmeloalencar** [Battlehub0x/RTE_Docs#77]
When I try to save any script in runtime on android this error happens, can someone help please. Have I wasted 4 hours trying?
I've tried it in 3 different versions of unity and it didn't work.

**Comment by samsgates** [comment]
script in runtime will work in only windows platform. it will not support android platform

**Comment by Battlehub0x** [comment]
I added the Assets/Battlehub/RTScripting.References.Android package, which allows you to run RTScripting on Android
