### ISSUE TITLE
center and pivot mode

### ISSUE THREAD

**Issue by BennyZong** [Battlehub0x/RTE_Docs#85]
there is no function When I changed the mode;
![image](https://github.com/Battlehub0x/RTE_Docs/assets/30481934/b271f856-b25b-4e06-bda8-5c05271c0b57)
there is no response when i changed the center and pivot，like the picture

**Comment by Battlehub0x** [comment]
![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/0ac316cd-154f-4978-8459-bd8cacf46e9c)
Fixed here https://github.com/Battlehub0x/RTE_AssetStore/issues/37

**Comment by BennyZong** [comment]
Sorry，What I means is when you choose a parent gameobject,It can focus on the center of all children(include parent).
Please see the pic,this is my goal.

![20230725175010](https://github.com/Battlehub0x/RTE_Docs/assets/30481934/197ffca3-66b7-444e-8d7f-9414b1443f56)
