### ISSUE TITLE
How can I add a new menu bar below main menu

### ISSUE THREAD

**Issue by BattlehubCode** [Battlehub0x/RTE_Docs#9]
How can I add a new menu bar below main menu and change postion of tool panel from main menu bar to new menu bar in run time editor.

**Comment by Battlehub0x** [comment]
Here's how to do it:

using Battlehub.RTEditor;
using UnityEngine;
using UnityEngine.UI;

public class SetTopBarExample : LayoutExtension
{
    [SerializeField]
    private RectTransform m_topBarPrefab = null;

    protected override void OnAfterBuildLayout(IWindowManager wm)
    {
        base.OnAfterBuildLayout(wm);

        wm.SetTools(null);

        RectTransform topBarTransform;
        if (m_topBarPrefab == null)
        {
            GameObject topBar = new GameObject();
            topBarTransform = topBar.AddComponent<RectTransform>();
            Image image = topBar.AddComponent<Image>();
            image.color = Color.red;

        }
        else
        {
            topBarTransform = Instantiate(m_topBarPrefab);
        }

        LayoutElement topBarLayout = topBarTransform.gameObject.AddComponent<LayoutElement>();
        topBarLayout.minHeight = 30;
        wm.SetTopBar(topBarTransform);
    }
}

![image](https://user-images.githubusercontent.com/15802443/158199539-4485d61b-9b8d-4d5f-bc73-948f92e54bbf.png)
