### ISSUE TITLE
The pivot point in the runtime editor is calculated differently than in the unity editor.

### ISSUE THREAD

**Issue by Battlehub0x** [Battlehub0x/RTE_Docs#90]
in unity，when I choose a parent gameobject,It can focus on the center of all children(include parent). but In RTE，it focus on the parent only

**Comment by Battlehub0x** [comment]
Hi, can you tell me more about this issue? It seems to work fine https://www.youtube.com/watch?v=J_SrJ-9aoAw

**Comment by Battlehub0x** [comment]
Benny 宗, [8/7/2023 10:39 AM]
center and pivot

Benny 宗, [8/7/2023 10:40 AM]
@WWWadik in unity，please see the pos of the Axis in the picture

![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/db978be3-d19f-486d-ba99-c3f6ef798116)

**Comment by nguyenph194812** [comment]
i came across a situation and wonder if it's a bug. When i select the object in RTE vs in Unity, the pivot is different. in the newest release i saw that the pivot can now be changed. Can you show me how ?

**Comment by Battlehub0x** [comment]
Additional fix for single object selection https://github.com/Battlehub0x/RTE_AssetStore/issues/43

**Comment by Battlehub0x** [comment]
I'm still keep doing things the old way. To enable UnityEditor-like behavior, set s_commonCenterStandardRTEBehaviour to false.

![image_2023-08-07_12-20-55](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/d9bb28aa-1d7b-415d-9364-e13e1c6cf1b5)
