### ISSUE TITLE
Is it possible to override the Play button?

### ISSUE THREAD

**Issue by Battlehub0x** [Battlehub0x/RTE_Docs#93]

**Comment by nomad5oul** [comment]
@Battlehub0x Is it possible to hide the Play button and if so how can this be done please?

Something like this maybe or another way?

    /// Hide existing menu item    
    [MenuCommand("MenuHelp/About RTE", hide: true)]
    public static void HideAbout() { }

**Comment by Battlehub0x** [comment]
Yes, create prefab variant of ToolsView

![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/b029107f-c722-43f0-9cf3-46901beda9f7)

Disable Play Toggle

![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/8a64922e-8b4b-4e4e-ac09-a26b8eb2035d)

And use ToolsView Variant instead of ToolsView

![image](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/bd8cdb95-8b3c-4f09-89f0-372e1cad8f4b)
