### ISSUE TITLE
Instantiated Prefabs that are dropped to Hierarchy,  are not visible in Hierarchy and not deleted from Scene in Unity with a version 2021.3.23f1.

### ISSUE THREAD

**Issue by rana-y** [Battlehub0x/RTE_Docs#94]
Regarding prefab representations visible in Project window, that are created via
(a) GlbImporterAsync::ImportAsync() function,
(b) "Create Prefab" menu in Hierarchy window, or
(c) Selecting object from Hierarchy Window and dropping it to Project window:

If the prefab is selected from Project window and dropped to Hierarchy window, 
(1) Instantiated object is listed in Hierarchy window as grayed-out and cannot be selected or modified,
(2) Instantiated object is not saved while saving scene via RuntimeEditor::SaveSceneAsync() function and
(3) 3D mesh of instantiated object in Scene window is not deleted throughout the session
(4) 3D mesh of instantiated object is visible on UnityEditor:Scene window even after exiting PlayMode.

**Test environment:**
RuntimeEditor version 3.5.3
Unity Editor version 2021.3.23f1

**Related screenshots:**
(1) If the prefab is selected from Project window and dropped to Hierarchy window, Instantiated object is listed in Hierarchy window as grayed-out.
![prefabBug_dropToHierarchy](https://github.com/Battlehub0x/RTE_Docs/assets/149372304/0aede284-9fa0-4789-80e9-6c73cbe4d053)

(2) Instantiated object is not saved while saving scene via RuntimeEditor::SaveSceneAsync() function
![prefabBug_afterNewScene](https://github.com/Battlehub0x/RTE_Docs/assets/149372304/d00167c9-9a4e-471b-b81f-c1cb3858fe86)

(3) 3D mesh of instantiated object in Scene window is not deleted throughout the session
![prefabBug_afterNewProject](https://github.com/Battlehub0x/RTE_Docs/assets/149372304/1ff06000-fb3b-4069-ae53-5dd0b5cc1744)

(4) 3D mesh of instantiated object is visible on UnityEditor:Scene window even after exiting PlayMode.
![prefabBug_afterExitPlay](https://github.com/Battlehub0x/RTE_Docs/assets/149372304/e88a7709-5cba-45ee-98e4-b5ee68094b2a)

**Comment by Battlehub0x** [comment]
Hi, unzip and import this package; after this the bug should disappear:
[Hierarchy_ClearHideFlags.zip](https://github.com/Battlehub0x/RTE_Docs/files/13248716/Hierarchy_ClearHideFlags.zip)

Fixed here: https://github.com/Battlehub0x/RTE_AssetStore/issues/41
